debug: true
logging:
    level:
        root: INFO
server:
    port: 9091
    servlet:
        context-path: /MIX-SALE
    session:
        timeout: 2m
spring:
    datasource:
        password: 12345678
        url: jdbc:mysql://localhost:3306/mixsale?useSSL=false
        username: root
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
        show-sql: true
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER

